#!/bin/bash

# Basic PBS script for testing your torque installation


## Inherit all current environment variables
#PBS -V


## Cluster Resources
#PBS -l nodes=2,walltime=00:10:00

# Job name
#PBS -N JobTest

## Keep Output and Error
#PBS -k eo

## Queue name
PBS -q my_queue

### Switch to the working directory;
cd /home/jobs

### Run:

STime=$(date +%s)

mpiexec -n 100 -f .machines seq 0 1000000000000000000000 > /dev/null

ETime=$(date +%s)

echo "Elapsed time: $(($ETime - $STime)) segundos" > job_time.log

